movie_list/movies/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'movie_list'
urlpatterns = [
    path('', views.index, name='index'),
    path('movie_list/<int:movie_list_id>/', views.view, name='view'),
    path('movie_list/new', views.new_movie_list, name='new'),
    path('movie_list/create', views.create_movie_list, name='create'),
    path('movie/new', views.new_movie_form, name='new_movie'),
    path('movie/create', views.create_movie, name='create_movie'),
    path('movie/add_to_list', views.add_movie_to_list, name='add_movie_to_list'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('log_out', views.log_user_out, name='log_out')
]

movie_list/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls'))
]

movie_list/movies/models.py
from django.contrib.auth.models import User
from django.db import models


class Movie(models.Model):
    name = models.CharField(max_length=500)
    release_year = models.IntegerField()
    genre = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class MovieList(models.Model):
    name = models.CharField(max_length=200, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    movies = models.ManyToManyField(Movie)

    def __str__(self):
        return self.name


class StarRanking(models.Model):
    ranking = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # there should be a unique constraint on (user_id, movie_id)

    def __str__(self):
        return "{movie_name}: {ranking} Star".format(movie_name=self.movie.name, ranking=self.ranking)

movie_list/movies/views.py
from django.contrib.auth import authenticate, logout, login as log_user_in
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from .models import MovieList, Movie
from .dao.movie_list import get_movie_lists, get_movie_list, add_movie_to_movie_list
from .dao.movie import get_movies_not_in_movie_list


def index(request):
    if request.user.is_authenticated:
        return render(request, 'movie_list/index.html', {'movie_lists': get_movie_lists(request.user.id)})
    return render(request, 'movie_list/index.html')


def view(request, movie_list_id):
    available_movies = get_movies_not_in_movie_list(movie_list_id)
    return render(request, 'movie_list/view.html', {
        'movie_list': get_movie_list(movie_list_id, request.user.id),
        'available_movies': available_movies
    })


def new_movie_list(request):
    return render(request, 'movie_list/new_movie_list.html')


def new_movie_form(request):
    return render(request, 'movie/new_movie_form.html')


@login_required
def create_movie(request):
    movie = Movie(name=request.POST['name'], release_year=request.POST['release_year'], genre=request.POST['genre'])
    movie.save()
    return redirect('/movies')


@login_required
def create_movie_list(request):
    movie_list = MovieList(name=request.POST['name'], user=request.user)
    movie_list.save()
    return view(request, movie_list.id)


def sign_up(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(username=form.cleaned_data.get('username'), password=form.cleaned_data.get('password1'))
            log_user_in(request, user)
            return redirect('/movies')

    form = UserCreationForm()
    return render(request, 'registration/sign_up.html', {'form': form})


def log_user_out(request):
    logout(request)
    return redirect('/movies')


@login_required()
def add_movie_to_list(request):
    print('HELLOOOO*****' + request.POST['movie_list_id'])
    add_movie_to_movie_list(request.POST['movie_id'], request.POST['movie_list_id'])
    return view(request, request.POST['movie_list_id'])


@login_required
def rate_movie(request, movie_id, rating):
    return

movie_list/movies/templates/movie/new_movie_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'movie_list:create_movie' %}" method="post">
    {% csrf_token %}
    <div>
        <label>movie title:</label>
        <input name="name" required>
    </div>
    <div>
        <label>release year:</label>
        <input name="release_year" required>
    </div>
    <div>
        <label>genre:</label>
        <input name="genre" required>
    </div>
    <button type="submit">CREATE THAT MOVIE</button>
</form>

</body>
</html>

movie_list/movies/templates/movie_list/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie List</title>
</head>
<body>
{% if not user.is_authenticated %}
    <div>
        <h3>you must login or sign up to create/view your movie lists</h3>
        <a href="{% url 'movie_list:login' %}">Login</a>
        <a href="{% url 'movie_list:sign_up' %}">Sign up</a>
    </div>
{% else %}
    <div>
        <a href="{% url 'movie_list:log_out' %}">Log out</a>
    </div>
    <div>
        <a href="{% url 'movie_list:new_movie' %}">Create a movie</a>
    </div>
    {% if movie_lists %}
        <ul>
        {% for movie_list in movie_lists %}
            <li><a href="{% url 'movie_list:view' movie_list.list.id %}">{{ movie_list.list.name }}</a></li>
            <p>Number of movies: {{ movie_list.number_of_movies }}</p>
            <p>Average rating: </p>
        {% endfor %}
        </ul>
    {% endif %}
{% endif %}
<a href="{% url 'movie_list:new' %}">Create a movie list!</a>

</body>
</html>

movie_list/movies/templates/movie_list/new_movie_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'movie_list:create' %}" method="post">
    {% csrf_token %}
    <label>name of your awesome movie list!</label>
    <input name="name" required>
    <button type="submit">CREATE THAT LIST</button>
</form>
</body>
</html>

movie_list/movies/templates/movie_list/view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'movie_list/movie_list.css' %}">
</head>
<body>
<a href="{% url 'movie_list:index' %}">see all my movie lists</a>
<h1>{{ movie_list.list.name }}</h1>
<hr/>
{% if available_movies %}
    <form action="{% url 'movie_list:add_movie_to_list'  %}" method="POST">
        {% csrf_token %}
        <div>
            <label>choose a movie to add to this list:</label>
            <select name="movie_id">
                <option disabled selected>select a movie!</option>
                {% for movie in available_movies %}
                    <option value="{{ movie.id }}" >{{ movie.name }}</option>
                {% endfor %}
            </select>
            <input type="hidden" name="movie_list_id" value="{{ movie_list.list.id }}">
            <button type="submit">ADD IT</button>
        </div>
    </form>
{% endif %}
{% if movie_list.movies %}
    <h2>Movies</h2>
    <div class="movieCardWrapper">
        {% for movie in movie_list.movies %}
            <div class="movieCard">
                <p><strong>Title:</strong> {{ movie.title }}</p>
                <p><strong>Released: </strong>{{ movie.release_year }}</p>
                <p><strong>Genre: </strong>{{ movie.genre }}</p>
                <p><strong>Average Rating: </strong>{{ movie.average_rating }}</p>
                <p><strong>My Rating: </strong> {{ movie.my_rating }}</p>
            </div>
        {% endfor %}
    </div>
{% endif %}
</body>
</html>